title: Daniel Müller
subtitle: Big Data Engineer and Data Scientist.
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog

# Edit these details

author_logo: profile.png
author: Daniel Müller
author_job: Big Data Engineer and Data Scientist.
author_bio: Hello, My Name is John Doe. I love to Code and Design. devlopr-jekyll is a theme built for developers.
author_email: "dmueller1607@gmail.com"
author_location: Germany
#author_website_url: "http://johndoe.com"

author_skills_programming_languages: Java, Scala, Python, SQL
author_skills_tools: Apache Hadoop / Spark / Kafka / HBase, Git, Windows, Linux

author_work_experiences:
            - company_name: Seamless Analytics GmbH
              company_logo: seamless_analytics_logo.png
              company_url: https://seamless-analytics.de
              designation: Gründer und Data Scientist
              description: Mitarbeit in verschiedenen Big Data Projekten
              visibility: true
            - company_name: SAP SE
              company_logo: sap_logo.png
              company_url: https://sap.com
              designation: Dualer Student
              description: Duales Studium (B.Sc.) Angewandte Informatik
              visibility: true

author_education_details:
              - college_logo: hs_offenburg.png
                college_name: HS Offenburg
                college_url: https://hs-offenburg.de
                college_degree: M.Sc. Informatik
                description: Master of Science, Informatik
                visibility: true
              - college_logo: dhbw_karlsruhe.png
                college_name: DHBW Karlsruhe
                college_url: https://www.karlsruhe.dhbw.de
                college_degree: B.Sc. Angewandte Informatik
                description: Bachelor of Science, Angewandte Informatik
                visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
github_username:  dmueller1607
facebook_username: dmueller1607
linkedin_username: dmueller1607

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# Build settings
theme: devlopr
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build