theme: devlopr
title: Seamless Analytics GmbH
description: This is our new Website :-)
show_downloads: true

github:
  is_project_page: true
  repository_url: https://github.com/dmueller1607/dmueller1607.github.io
